### PR TITLE
fix yarn lock after merging in source strapi

### PR DESCRIPTION
**Pull request by laurenskling**

### CODE REVIEW

**Comment by laurenskling** [comment]
@moonmeister does this need a changeset now?

**Comment by moonmeister** [comment]
Nope

**Review by moonmeister — APPROVED** [review]

**Comment by moonmeister** [comment]
So the Gatsby build was failing cause of this on the original PR but our GH Action tests were passing...not sure why ?! 🤔 At least until we merged. 🤷‍♂️

**Comment by laurenskling** [comment]
I guess since we played around with the deps in the package.json it was ony a hard lock file error, and not the actual packages installed

**Pull request merged**
