### PR TITLE
feat(gatsby-source-strapi): Limit parallel requests to api

### PR DESCRIPTION
**Pull request by fr0stylo**
## Description

Adding max parallel limit for entities array list

### Documentation

Added additional strapi config `maxParallelRequests` to plugin config.
Updated README.md

## Related Issues

Implements #372

### CODE REVIEW

**Comment by moonmeister** [comment]
I don't believe we've automated tests yet for this plugin. Have you run the integration tests for it manually from the integration-test folder? Should be a variety of site builds.

**Comment by fr0stylo** [comment]
No I haven't. Ill try to do so

**Comment by fr0stylo** [comment]
I tested this approach on my own project.

**Comment by moonmeister** [comment]
> I wonder @moonmeister @laurenskling @fr0stylo should the limiting on the parallel requests be done also in the download files part? I noticed that I may have network dropping requests with many media files being downloaded at the same time 🤔 

My very ignorant response would be that all files being downloaded, images or otherwise, should be throttled under the same control.

**Comment by fr0stylo** [comment]
I think so, small problem here is that currently is a flow we `Promise.all(catergories -> ..)` and  then it branches to other `Promise.all(entities -> ...)` and `Promise.all(media -> ...)`. The whole request tree needs to be throttled I think, which is a bit difficult then current solution.

**Comment by konsalex** [comment]
Maybe a simple singleton export @fr0stylo that will incorporate a counter that will be used by all of them? Not sure about the exact flow though so take it with pinch of salt

**Comment by konsalex** [comment]
Also can see that there are many axios instances in the code, if this could import a singleton (single axios instance in all of them), you could even create a simple interceptor (inspo here: https://gist.github.com/matthewsuan/2bdc9e7f459d5b073d58d1ebc0613169) to delegate the parallel requests.

Any drawbacks in this approach @moonmeister ?

**Comment by moonmeister** [comment]
> Also can see that there are many axios instances in the code, if this could import a singleton (single axios instance in all of them), you could even create a simple interceptor (inspo here: https://gist.github.com/matthewsuan/2bdc9e7f459d5b073d58d1ebc0613169) to delegate the parallel requests.
> 
> Any drawbacks in this approach @moonmeister ?

This makes the most sense, axios seems like the correct layer for this kind of work.

**Pull request closed without merging**
