### PR TITLE
fix(packages): homepage links in package.json

### PR DESCRIPTION
**Pull request by tboutron**
## Description

Fixed homepage links of packages.
Homepage are currently broken / unset for almost all plugins and it's annoying to navigate manually :)

### CODE REVIEW

**Comment by moonmeister** [comment]
If you could add some release notes I'll get this merge. From the root please run `yarn cs` and do a patch bump. Thanks for the PR, it's the little things!

**Comment by tboutron** [comment]
@moonmeister done !

**Comment by moonmeister** [comment]
Not seeing the change log. That created a file you need to push up.

**Review by moonmeister — APPROVED** [review]

**Comment by moonmeister** [comment]
Thank! much appreciated

**Comment by moonmeister** [comment]
Looks like we just need to run prettier.

**Pull request merged**
